- name: Create ufw config file
  become: yes
  template:
    src: "templates/ufw.j2"
    dest: /etc/default/ufw
    owner: root
    mode: "0644"

- name: Enable UFW
  become: yes
  community.general.ufw:
    state: enabled
    default: deny

# https://debian-administration.org/article/187/Using_iptables_to_rate-limit_incoming_connections
- name: "Prevent brute-force attacks on ssh port {{ ethv_ssh_port }}"
  become: yes
  community.general.ufw:
    rule: limit
    port: "{{ ethv_ssh_port }}"
    proto: tcp

- name: Allow Go Ethereum
  become: yes
  community.general.ufw:
    rule: allow
    port: '30303'

- name: Allow Prysm Validator Client TCP
  become: yes
  community.general.ufw:
    rule: allow
    port: '13000'
    proto: tcp

- name: Allow Prysm Validator Client UDP
  become: yes
  community.general.ufw:
    rule: allow
    port: '12000'
    proto: udp

- name: Allow Grafana Monitoring
  become: yes
  community.general.ufw:
    rule: allow
    port: '{{ ethv_grafana_port }}'
    proto: tcp
  when:
    - ethv_monitoring
    - ethv_monitoring_expose
