- name: Make sure ntp package is absent
  become: yes
  apt:
    name: ntp
    state: absent

- name: Create timesyncd.conf
  become: yes
  template:
    src: templates/timesyncd.conf.j2
    dest: "/etc/systemd/timesyncd.conf"
    mode: '0644'
    owner: root
    group: root

- name: Check timedatectl
  command: "timedatectl status"
  register: timedatectl_output

- name: Enable timesyncd
  become: yes
  command: "timedatectl set-ntp on"
  when: "'NTP service: active' not in timedatectl_output.stdout"

- name: Enable ntp service
  become: yes
  command: "systemctl enable --now systemd-timesyncd"

- name: Run timedatectl show
  command: "timedatectl show"
  register: timedatectl_output
  retries: 20
  delay: 10
  until: "'NTPSynchronized=yes' in timedatectl_output.stdout"
